version: 2.1
orbs:
  ruby: circleci/ruby@1.1.0

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.1.4
      - ruby/rubocop-check
      - ruby/rspec-test
